alter table DEMO_APPLICANT add constraint FK_DEMO_APPLICANT_ON_VEHICLE_TYPE foreign key (VEHICLE_TYPE_ID) references DEMO_VEHICLE_TYPE(ID);
create index IDX_DEMO_APPLICANT_ON_VEHICLE_TYPE on DEMO_APPLICANT (VEHICLE_TYPE_ID);
